/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDeepCoursesRouteImport } from './routes/_authed/deep-courses'
import { Route as AuthedChatRouteImport } from './routes/_authed/chat'
import { Route as AuthedPostsRouteRouteImport } from './routes/_authed/posts.route'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as AuthedDeepCoursesIndexRouteImport } from './routes/_authed/deep-courses.index'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'
import { Route as AuthedDeepCoursesCourseIdRouteImport } from './routes/_authed/deep-courses.$courseId'
import { Route as AuthedChatChatIdRouteImport } from './routes/_authed/chat.$chatId'
import { Route as AuthedDeepCoursesCourseIdIndexRouteImport } from './routes/_authed/deep-courses.$courseId.index'
import { Route as AuthedDeepCoursesCourseIdChapterIdRouteImport } from './routes/_authed/deep-courses.$courseId.$chapterId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDeepCoursesRoute = AuthedDeepCoursesRouteImport.update({
  id: '/deep-courses',
  path: '/deep-courses',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsRouteRoute = AuthedPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const AuthedDeepCoursesIndexRoute = AuthedDeepCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDeepCoursesRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const AuthedDeepCoursesCourseIdRoute =
  AuthedDeepCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthedDeepCoursesRoute,
  } as any)
const AuthedChatChatIdRoute = AuthedChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthedChatRoute,
} as any)
const AuthedDeepCoursesCourseIdIndexRoute =
  AuthedDeepCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDeepCoursesCourseIdRoute,
  } as any)
const AuthedDeepCoursesCourseIdChapterIdRoute =
  AuthedDeepCoursesCourseIdChapterIdRouteImport.update({
    id: '/$chapterId',
    path: '/$chapterId',
    getParentRoute: () => AuthedDeepCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/posts': typeof AuthedPostsRouteRouteWithChildren
  '/chat': typeof AuthedChatRouteWithChildren
  '/deep-courses': typeof AuthedDeepCoursesRouteWithChildren
  '/chat/$chatId': typeof AuthedChatChatIdRoute
  '/deep-courses/$courseId': typeof AuthedDeepCoursesCourseIdRouteWithChildren
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/deep-courses/': typeof AuthedDeepCoursesIndexRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/deep-courses/$courseId/$chapterId': typeof AuthedDeepCoursesCourseIdChapterIdRoute
  '/deep-courses/$courseId/': typeof AuthedDeepCoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AuthedChatRouteWithChildren
  '/chat/$chatId': typeof AuthedChatChatIdRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/deep-courses': typeof AuthedDeepCoursesIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/deep-courses/$courseId/$chapterId': typeof AuthedDeepCoursesCourseIdChapterIdRoute
  '/deep-courses/$courseId': typeof AuthedDeepCoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/_authed/posts': typeof AuthedPostsRouteRouteWithChildren
  '/_authed/chat': typeof AuthedChatRouteWithChildren
  '/_authed/deep-courses': typeof AuthedDeepCoursesRouteWithChildren
  '/_authed/chat/$chatId': typeof AuthedChatChatIdRoute
  '/_authed/deep-courses/$courseId': typeof AuthedDeepCoursesCourseIdRouteWithChildren
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/deep-courses/': typeof AuthedDeepCoursesIndexRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/_authed/deep-courses/$courseId/$chapterId': typeof AuthedDeepCoursesCourseIdChapterIdRoute
  '/_authed/deep-courses/$courseId/': typeof AuthedDeepCoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/signup'
    | '/posts'
    | '/chat'
    | '/deep-courses'
    | '/chat/$chatId'
    | '/deep-courses/$courseId'
    | '/posts/$postId'
    | '/deep-courses/'
    | '/posts/'
    | '/deep-courses/$courseId/$chapterId'
    | '/deep-courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/signup'
    | '/chat'
    | '/chat/$chatId'
    | '/posts/$postId'
    | '/deep-courses'
    | '/posts'
    | '/deep-courses/$courseId/$chapterId'
    | '/deep-courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/signup'
    | '/_authed/posts'
    | '/_authed/chat'
    | '/_authed/deep-courses'
    | '/_authed/chat/$chatId'
    | '/_authed/deep-courses/$courseId'
    | '/_authed/posts/$postId'
    | '/_authed/deep-courses/'
    | '/_authed/posts/'
    | '/_authed/deep-courses/$courseId/$chapterId'
    | '/_authed/deep-courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/deep-courses': {
      id: '/_authed/deep-courses'
      path: '/deep-courses'
      fullPath: '/deep-courses'
      preLoaderRoute: typeof AuthedDeepCoursesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/_authed/deep-courses/': {
      id: '/_authed/deep-courses/'
      path: '/'
      fullPath: '/deep-courses/'
      preLoaderRoute: typeof AuthedDeepCoursesIndexRouteImport
      parentRoute: typeof AuthedDeepCoursesRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/_authed/deep-courses/$courseId': {
      id: '/_authed/deep-courses/$courseId'
      path: '/$courseId'
      fullPath: '/deep-courses/$courseId'
      preLoaderRoute: typeof AuthedDeepCoursesCourseIdRouteImport
      parentRoute: typeof AuthedDeepCoursesRoute
    }
    '/_authed/chat/$chatId': {
      id: '/_authed/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AuthedChatChatIdRouteImport
      parentRoute: typeof AuthedChatRoute
    }
    '/_authed/deep-courses/$courseId/': {
      id: '/_authed/deep-courses/$courseId/'
      path: '/'
      fullPath: '/deep-courses/$courseId/'
      preLoaderRoute: typeof AuthedDeepCoursesCourseIdIndexRouteImport
      parentRoute: typeof AuthedDeepCoursesCourseIdRoute
    }
    '/_authed/deep-courses/$courseId/$chapterId': {
      id: '/_authed/deep-courses/$courseId/$chapterId'
      path: '/$chapterId'
      fullPath: '/deep-courses/$courseId/$chapterId'
      preLoaderRoute: typeof AuthedDeepCoursesCourseIdChapterIdRouteImport
      parentRoute: typeof AuthedDeepCoursesCourseIdRoute
    }
  }
}

interface AuthedPostsRouteRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteRouteChildren: AuthedPostsRouteRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteRouteWithChildren =
  AuthedPostsRouteRoute._addFileChildren(AuthedPostsRouteRouteChildren)

interface AuthedChatRouteChildren {
  AuthedChatChatIdRoute: typeof AuthedChatChatIdRoute
}

const AuthedChatRouteChildren: AuthedChatRouteChildren = {
  AuthedChatChatIdRoute: AuthedChatChatIdRoute,
}

const AuthedChatRouteWithChildren = AuthedChatRoute._addFileChildren(
  AuthedChatRouteChildren,
)

interface AuthedDeepCoursesCourseIdRouteChildren {
  AuthedDeepCoursesCourseIdChapterIdRoute: typeof AuthedDeepCoursesCourseIdChapterIdRoute
  AuthedDeepCoursesCourseIdIndexRoute: typeof AuthedDeepCoursesCourseIdIndexRoute
}

const AuthedDeepCoursesCourseIdRouteChildren: AuthedDeepCoursesCourseIdRouteChildren =
  {
    AuthedDeepCoursesCourseIdChapterIdRoute:
      AuthedDeepCoursesCourseIdChapterIdRoute,
    AuthedDeepCoursesCourseIdIndexRoute: AuthedDeepCoursesCourseIdIndexRoute,
  }

const AuthedDeepCoursesCourseIdRouteWithChildren =
  AuthedDeepCoursesCourseIdRoute._addFileChildren(
    AuthedDeepCoursesCourseIdRouteChildren,
  )

interface AuthedDeepCoursesRouteChildren {
  AuthedDeepCoursesCourseIdRoute: typeof AuthedDeepCoursesCourseIdRouteWithChildren
  AuthedDeepCoursesIndexRoute: typeof AuthedDeepCoursesIndexRoute
}

const AuthedDeepCoursesRouteChildren: AuthedDeepCoursesRouteChildren = {
  AuthedDeepCoursesCourseIdRoute: AuthedDeepCoursesCourseIdRouteWithChildren,
  AuthedDeepCoursesIndexRoute: AuthedDeepCoursesIndexRoute,
}

const AuthedDeepCoursesRouteWithChildren =
  AuthedDeepCoursesRoute._addFileChildren(AuthedDeepCoursesRouteChildren)

interface AuthedRouteChildren {
  AuthedPostsRouteRoute: typeof AuthedPostsRouteRouteWithChildren
  AuthedChatRoute: typeof AuthedChatRouteWithChildren
  AuthedDeepCoursesRoute: typeof AuthedDeepCoursesRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPostsRouteRoute: AuthedPostsRouteRouteWithChildren,
  AuthedChatRoute: AuthedChatRouteWithChildren,
  AuthedDeepCoursesRoute: AuthedDeepCoursesRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CalendarRoute: CalendarRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
