/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDeepCoursesRouteImport } from './routes/_authed/deep-courses'
import { Route as AuthedPostsRouteRouteImport } from './routes/_authed/posts.route'
import { Route as AuthedCourseRouteRouteImport } from './routes/_authed/course/route'
import { Route as AuthedChatRouteRouteImport } from './routes/_authed/chat/route'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as AuthedDeepCoursesIndexRouteImport } from './routes/_authed/deep-courses.index'
import { Route as AuthedCourseIndexRouteImport } from './routes/_authed/course/index'
import { Route as AuthedChatIndexRouteImport } from './routes/_authed/chat/index'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'
import { Route as AuthedLayer_layoutRouteImport } from './routes/_authed/layer/__layout'
import { Route as AuthedDeepCourses_layoutRouteImport } from './routes/_authed/deep-courses/__layout'
import { Route as AuthedDeepCoursesCourseIdRouteImport } from './routes/_authed/deep-courses.$courseId'
import { Route as AuthedCourseIdRouteImport } from './routes/_authed/course/$id'
import { Route as AuthedChatIdRouteImport } from './routes/_authed/chat/$id'
import { Route as AuthedDeepCoursesCourseIdIndexRouteImport } from './routes/_authed/deep-courses.$courseId.index'
import { Route as AuthedDeepCoursesCourseIdChapterIdRouteImport } from './routes/_authed/deep-courses.$courseId.$chapterId'

const AuthedLayerRouteImport = createFileRoute('/_authed/layer')()

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayerRoute = AuthedLayerRouteImport.update({
  id: '/layer',
  path: '/layer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeepCoursesRoute = AuthedDeepCoursesRouteImport.update({
  id: '/deep-courses',
  path: '/deep-courses',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsRouteRoute = AuthedPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCourseRouteRoute = AuthedCourseRouteRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatRouteRoute = AuthedChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const AuthedDeepCoursesIndexRoute = AuthedDeepCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDeepCoursesRoute,
} as any)
const AuthedCourseIndexRoute = AuthedCourseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCourseRouteRoute,
} as any)
const AuthedChatIndexRoute = AuthedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedChatRouteRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const AuthedLayer_layoutRoute = AuthedLayer_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => AuthedLayerRoute,
} as any)
const AuthedDeepCourses_layoutRoute =
  AuthedDeepCourses_layoutRouteImport.update({
    id: '/__layout',
    getParentRoute: () => AuthedDeepCoursesRoute,
  } as any)
const AuthedDeepCoursesCourseIdRoute =
  AuthedDeepCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthedDeepCoursesRoute,
  } as any)
const AuthedCourseIdRoute = AuthedCourseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedCourseRouteRoute,
} as any)
const AuthedChatIdRoute = AuthedChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedChatRouteRoute,
} as any)
const AuthedDeepCoursesCourseIdIndexRoute =
  AuthedDeepCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDeepCoursesCourseIdRoute,
  } as any)
const AuthedDeepCoursesCourseIdChapterIdRoute =
  AuthedDeepCoursesCourseIdChapterIdRouteImport.update({
    id: '/$chapterId',
    path: '/$chapterId',
    getParentRoute: () => AuthedDeepCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AuthedChatRouteRouteWithChildren
  '/course': typeof AuthedCourseRouteRouteWithChildren
  '/posts': typeof AuthedPostsRouteRouteWithChildren
  '/deep-courses': typeof AuthedDeepCourses_layoutRoute
  '/chat/$id': typeof AuthedChatIdRoute
  '/course/$id': typeof AuthedCourseIdRoute
  '/deep-courses/$courseId': typeof AuthedDeepCoursesCourseIdRouteWithChildren
  '/layer': typeof AuthedLayer_layoutRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/chat/': typeof AuthedChatIndexRoute
  '/course/': typeof AuthedCourseIndexRoute
  '/deep-courses/': typeof AuthedDeepCoursesIndexRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/deep-courses/$courseId/$chapterId': typeof AuthedDeepCoursesCourseIdChapterIdRoute
  '/deep-courses/$courseId/': typeof AuthedDeepCoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/chat/$id': typeof AuthedChatIdRoute
  '/course/$id': typeof AuthedCourseIdRoute
  '/deep-courses': typeof AuthedDeepCoursesIndexRoute
  '/layer': typeof AuthedLayer_layoutRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/chat': typeof AuthedChatIndexRoute
  '/course': typeof AuthedCourseIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/deep-courses/$courseId/$chapterId': typeof AuthedDeepCoursesCourseIdChapterIdRoute
  '/deep-courses/$courseId': typeof AuthedDeepCoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/_authed/chat': typeof AuthedChatRouteRouteWithChildren
  '/_authed/course': typeof AuthedCourseRouteRouteWithChildren
  '/_authed/posts': typeof AuthedPostsRouteRouteWithChildren
  '/_authed/deep-courses': typeof AuthedDeepCoursesRouteWithChildren
  '/_authed/chat/$id': typeof AuthedChatIdRoute
  '/_authed/course/$id': typeof AuthedCourseIdRoute
  '/_authed/deep-courses/$courseId': typeof AuthedDeepCoursesCourseIdRouteWithChildren
  '/_authed/deep-courses/__layout': typeof AuthedDeepCourses_layoutRoute
  '/_authed/layer': typeof AuthedLayerRouteWithChildren
  '/_authed/layer/__layout': typeof AuthedLayer_layoutRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/chat/': typeof AuthedChatIndexRoute
  '/_authed/course/': typeof AuthedCourseIndexRoute
  '/_authed/deep-courses/': typeof AuthedDeepCoursesIndexRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/_authed/deep-courses/$courseId/$chapterId': typeof AuthedDeepCoursesCourseIdChapterIdRoute
  '/_authed/deep-courses/$courseId/': typeof AuthedDeepCoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/signup'
    | '/chat'
    | '/course'
    | '/posts'
    | '/deep-courses'
    | '/chat/$id'
    | '/course/$id'
    | '/deep-courses/$courseId'
    | '/layer'
    | '/posts/$postId'
    | '/chat/'
    | '/course/'
    | '/deep-courses/'
    | '/posts/'
    | '/deep-courses/$courseId/$chapterId'
    | '/deep-courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/signup'
    | '/chat/$id'
    | '/course/$id'
    | '/deep-courses'
    | '/layer'
    | '/posts/$postId'
    | '/chat'
    | '/course'
    | '/posts'
    | '/deep-courses/$courseId/$chapterId'
    | '/deep-courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/signup'
    | '/_authed/chat'
    | '/_authed/course'
    | '/_authed/posts'
    | '/_authed/deep-courses'
    | '/_authed/chat/$id'
    | '/_authed/course/$id'
    | '/_authed/deep-courses/$courseId'
    | '/_authed/deep-courses/__layout'
    | '/_authed/layer'
    | '/_authed/layer/__layout'
    | '/_authed/posts/$postId'
    | '/_authed/chat/'
    | '/_authed/course/'
    | '/_authed/deep-courses/'
    | '/_authed/posts/'
    | '/_authed/deep-courses/$courseId/$chapterId'
    | '/_authed/deep-courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/layer': {
      id: '/_authed/layer'
      path: '/layer'
      fullPath: '/layer'
      preLoaderRoute: typeof AuthedLayerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deep-courses': {
      id: '/_authed/deep-courses'
      path: '/deep-courses'
      fullPath: '/deep-courses'
      preLoaderRoute: typeof AuthedDeepCoursesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/course': {
      id: '/_authed/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof AuthedCourseRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/_authed/deep-courses/': {
      id: '/_authed/deep-courses/'
      path: '/'
      fullPath: '/deep-courses/'
      preLoaderRoute: typeof AuthedDeepCoursesIndexRouteImport
      parentRoute: typeof AuthedDeepCoursesRoute
    }
    '/_authed/course/': {
      id: '/_authed/course/'
      path: '/'
      fullPath: '/course/'
      preLoaderRoute: typeof AuthedCourseIndexRouteImport
      parentRoute: typeof AuthedCourseRouteRoute
    }
    '/_authed/chat/': {
      id: '/_authed/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthedChatIndexRouteImport
      parentRoute: typeof AuthedChatRouteRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/_authed/layer/__layout': {
      id: '/_authed/layer/__layout'
      path: '/layer'
      fullPath: '/layer'
      preLoaderRoute: typeof AuthedLayer_layoutRouteImport
      parentRoute: typeof AuthedLayerRoute
    }
    '/_authed/deep-courses/__layout': {
      id: '/_authed/deep-courses/__layout'
      path: ''
      fullPath: '/deep-courses'
      preLoaderRoute: typeof AuthedDeepCourses_layoutRouteImport
      parentRoute: typeof AuthedDeepCoursesRoute
    }
    '/_authed/deep-courses/$courseId': {
      id: '/_authed/deep-courses/$courseId'
      path: '/$courseId'
      fullPath: '/deep-courses/$courseId'
      preLoaderRoute: typeof AuthedDeepCoursesCourseIdRouteImport
      parentRoute: typeof AuthedDeepCoursesRoute
    }
    '/_authed/course/$id': {
      id: '/_authed/course/$id'
      path: '/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof AuthedCourseIdRouteImport
      parentRoute: typeof AuthedCourseRouteRoute
    }
    '/_authed/chat/$id': {
      id: '/_authed/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthedChatIdRouteImport
      parentRoute: typeof AuthedChatRouteRoute
    }
    '/_authed/deep-courses/$courseId/': {
      id: '/_authed/deep-courses/$courseId/'
      path: '/'
      fullPath: '/deep-courses/$courseId/'
      preLoaderRoute: typeof AuthedDeepCoursesCourseIdIndexRouteImport
      parentRoute: typeof AuthedDeepCoursesCourseIdRoute
    }
    '/_authed/deep-courses/$courseId/$chapterId': {
      id: '/_authed/deep-courses/$courseId/$chapterId'
      path: '/$chapterId'
      fullPath: '/deep-courses/$courseId/$chapterId'
      preLoaderRoute: typeof AuthedDeepCoursesCourseIdChapterIdRouteImport
      parentRoute: typeof AuthedDeepCoursesCourseIdRoute
    }
  }
}

interface AuthedChatRouteRouteChildren {
  AuthedChatIdRoute: typeof AuthedChatIdRoute
  AuthedChatIndexRoute: typeof AuthedChatIndexRoute
}

const AuthedChatRouteRouteChildren: AuthedChatRouteRouteChildren = {
  AuthedChatIdRoute: AuthedChatIdRoute,
  AuthedChatIndexRoute: AuthedChatIndexRoute,
}

const AuthedChatRouteRouteWithChildren = AuthedChatRouteRoute._addFileChildren(
  AuthedChatRouteRouteChildren,
)

interface AuthedCourseRouteRouteChildren {
  AuthedCourseIdRoute: typeof AuthedCourseIdRoute
  AuthedCourseIndexRoute: typeof AuthedCourseIndexRoute
}

const AuthedCourseRouteRouteChildren: AuthedCourseRouteRouteChildren = {
  AuthedCourseIdRoute: AuthedCourseIdRoute,
  AuthedCourseIndexRoute: AuthedCourseIndexRoute,
}

const AuthedCourseRouteRouteWithChildren =
  AuthedCourseRouteRoute._addFileChildren(AuthedCourseRouteRouteChildren)

interface AuthedPostsRouteRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteRouteChildren: AuthedPostsRouteRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteRouteWithChildren =
  AuthedPostsRouteRoute._addFileChildren(AuthedPostsRouteRouteChildren)

interface AuthedDeepCoursesCourseIdRouteChildren {
  AuthedDeepCoursesCourseIdChapterIdRoute: typeof AuthedDeepCoursesCourseIdChapterIdRoute
  AuthedDeepCoursesCourseIdIndexRoute: typeof AuthedDeepCoursesCourseIdIndexRoute
}

const AuthedDeepCoursesCourseIdRouteChildren: AuthedDeepCoursesCourseIdRouteChildren =
  {
    AuthedDeepCoursesCourseIdChapterIdRoute:
      AuthedDeepCoursesCourseIdChapterIdRoute,
    AuthedDeepCoursesCourseIdIndexRoute: AuthedDeepCoursesCourseIdIndexRoute,
  }

const AuthedDeepCoursesCourseIdRouteWithChildren =
  AuthedDeepCoursesCourseIdRoute._addFileChildren(
    AuthedDeepCoursesCourseIdRouteChildren,
  )

interface AuthedDeepCoursesRouteChildren {
  AuthedDeepCoursesCourseIdRoute: typeof AuthedDeepCoursesCourseIdRouteWithChildren
  AuthedDeepCourses_layoutRoute: typeof AuthedDeepCourses_layoutRoute
  AuthedDeepCoursesIndexRoute: typeof AuthedDeepCoursesIndexRoute
}

const AuthedDeepCoursesRouteChildren: AuthedDeepCoursesRouteChildren = {
  AuthedDeepCoursesCourseIdRoute: AuthedDeepCoursesCourseIdRouteWithChildren,
  AuthedDeepCourses_layoutRoute: AuthedDeepCourses_layoutRoute,
  AuthedDeepCoursesIndexRoute: AuthedDeepCoursesIndexRoute,
}

const AuthedDeepCoursesRouteWithChildren =
  AuthedDeepCoursesRoute._addFileChildren(AuthedDeepCoursesRouteChildren)

interface AuthedLayerRouteChildren {
  AuthedLayer_layoutRoute: typeof AuthedLayer_layoutRoute
}

const AuthedLayerRouteChildren: AuthedLayerRouteChildren = {
  AuthedLayer_layoutRoute: AuthedLayer_layoutRoute,
}

const AuthedLayerRouteWithChildren = AuthedLayerRoute._addFileChildren(
  AuthedLayerRouteChildren,
)

interface AuthedRouteChildren {
  AuthedChatRouteRoute: typeof AuthedChatRouteRouteWithChildren
  AuthedCourseRouteRoute: typeof AuthedCourseRouteRouteWithChildren
  AuthedPostsRouteRoute: typeof AuthedPostsRouteRouteWithChildren
  AuthedDeepCoursesRoute: typeof AuthedDeepCoursesRouteWithChildren
  AuthedLayerRoute: typeof AuthedLayerRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatRouteRoute: AuthedChatRouteRouteWithChildren,
  AuthedCourseRouteRoute: AuthedCourseRouteRouteWithChildren,
  AuthedPostsRouteRoute: AuthedPostsRouteRouteWithChildren,
  AuthedDeepCoursesRoute: AuthedDeepCoursesRouteWithChildren,
  AuthedLayerRoute: AuthedLayerRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CalendarRoute: CalendarRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
