/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDeepCourseRouteImport } from './routes/_authed/deep-course'
import { Route as AuthedPostsRouteRouteImport } from './routes/_authed/posts.route'
import { Route as AuthedExerciseRouteRouteImport } from './routes/_authed/exercise/route'
import { Route as AuthedCourseRouteRouteImport } from './routes/_authed/course/route'
import { Route as AuthedChatRouteRouteImport } from './routes/_authed/chat/route'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as AuthedExerciseIndexRouteImport } from './routes/_authed/exercise/index'
import { Route as AuthedDeepCourseIndexRouteImport } from './routes/_authed/deep-course/index'
import { Route as AuthedCourseIndexRouteImport } from './routes/_authed/course/index'
import { Route as AuthedChatIndexRouteImport } from './routes/_authed/chat/index'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'
import { Route as AuthedLayer_layoutRouteImport } from './routes/_authed/layer/__layout'
import { Route as AuthedExerciseIdRouteImport } from './routes/_authed/exercise/$id'
import { Route as AuthedDeepCourseDeepcourseIdRouteImport } from './routes/_authed/deep-course/$deepcourseId'
import { Route as AuthedCourseIdRouteImport } from './routes/_authed/course/$id'
import { Route as AuthedChatIdRouteImport } from './routes/_authed/chat/$id'
import { Route as AuthedDeepCourseDeepcourseIdChapterIdRouteImport } from './routes/_authed/deep-course/$deepcourseId/$chapterId'

const AuthedLayerRouteImport = createFileRoute('/_authed/layer')()

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayerRoute = AuthedLayerRouteImport.update({
  id: '/layer',
  path: '/layer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeepCourseRoute = AuthedDeepCourseRouteImport.update({
  id: '/deep-course',
  path: '/deep-course',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsRouteRoute = AuthedPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExerciseRouteRoute = AuthedExerciseRouteRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCourseRouteRoute = AuthedCourseRouteRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatRouteRoute = AuthedChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const AuthedExerciseIndexRoute = AuthedExerciseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedExerciseRouteRoute,
} as any)
const AuthedDeepCourseIndexRoute = AuthedDeepCourseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDeepCourseRoute,
} as any)
const AuthedCourseIndexRoute = AuthedCourseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCourseRouteRoute,
} as any)
const AuthedChatIndexRoute = AuthedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedChatRouteRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const AuthedLayer_layoutRoute = AuthedLayer_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => AuthedLayerRoute,
} as any)
const AuthedExerciseIdRoute = AuthedExerciseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedExerciseRouteRoute,
} as any)
const AuthedDeepCourseDeepcourseIdRoute =
  AuthedDeepCourseDeepcourseIdRouteImport.update({
    id: '/$deepcourseId',
    path: '/$deepcourseId',
    getParentRoute: () => AuthedDeepCourseRoute,
  } as any)
const AuthedCourseIdRoute = AuthedCourseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedCourseRouteRoute,
} as any)
const AuthedChatIdRoute = AuthedChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedChatRouteRoute,
} as any)
const AuthedDeepCourseDeepcourseIdChapterIdRoute =
  AuthedDeepCourseDeepcourseIdChapterIdRouteImport.update({
    id: '/$chapterId',
    path: '/$chapterId',
    getParentRoute: () => AuthedDeepCourseDeepcourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AuthedChatRouteRouteWithChildren
  '/course': typeof AuthedCourseRouteRouteWithChildren
  '/exercise': typeof AuthedExerciseRouteRouteWithChildren
  '/posts': typeof AuthedPostsRouteRouteWithChildren
  '/deep-course': typeof AuthedDeepCourseRouteWithChildren
  '/chat/$id': typeof AuthedChatIdRoute
  '/course/$id': typeof AuthedCourseIdRoute
  '/deep-course/$deepcourseId': typeof AuthedDeepCourseDeepcourseIdRouteWithChildren
  '/exercise/$id': typeof AuthedExerciseIdRoute
  '/layer': typeof AuthedLayer_layoutRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/chat/': typeof AuthedChatIndexRoute
  '/course/': typeof AuthedCourseIndexRoute
  '/deep-course/': typeof AuthedDeepCourseIndexRoute
  '/exercise/': typeof AuthedExerciseIndexRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/deep-course/$deepcourseId/$chapterId': typeof AuthedDeepCourseDeepcourseIdChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/chat/$id': typeof AuthedChatIdRoute
  '/course/$id': typeof AuthedCourseIdRoute
  '/deep-course/$deepcourseId': typeof AuthedDeepCourseDeepcourseIdRouteWithChildren
  '/exercise/$id': typeof AuthedExerciseIdRoute
  '/layer': typeof AuthedLayer_layoutRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/chat': typeof AuthedChatIndexRoute
  '/course': typeof AuthedCourseIndexRoute
  '/deep-course': typeof AuthedDeepCourseIndexRoute
  '/exercise': typeof AuthedExerciseIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/deep-course/$deepcourseId/$chapterId': typeof AuthedDeepCourseDeepcourseIdChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/_authed/chat': typeof AuthedChatRouteRouteWithChildren
  '/_authed/course': typeof AuthedCourseRouteRouteWithChildren
  '/_authed/exercise': typeof AuthedExerciseRouteRouteWithChildren
  '/_authed/posts': typeof AuthedPostsRouteRouteWithChildren
  '/_authed/deep-course': typeof AuthedDeepCourseRouteWithChildren
  '/_authed/chat/$id': typeof AuthedChatIdRoute
  '/_authed/course/$id': typeof AuthedCourseIdRoute
  '/_authed/deep-course/$deepcourseId': typeof AuthedDeepCourseDeepcourseIdRouteWithChildren
  '/_authed/exercise/$id': typeof AuthedExerciseIdRoute
  '/_authed/layer': typeof AuthedLayerRouteWithChildren
  '/_authed/layer/__layout': typeof AuthedLayer_layoutRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/chat/': typeof AuthedChatIndexRoute
  '/_authed/course/': typeof AuthedCourseIndexRoute
  '/_authed/deep-course/': typeof AuthedDeepCourseIndexRoute
  '/_authed/exercise/': typeof AuthedExerciseIndexRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/_authed/deep-course/$deepcourseId/$chapterId': typeof AuthedDeepCourseDeepcourseIdChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/signup'
    | '/chat'
    | '/course'
    | '/exercise'
    | '/posts'
    | '/deep-course'
    | '/chat/$id'
    | '/course/$id'
    | '/deep-course/$deepcourseId'
    | '/exercise/$id'
    | '/layer'
    | '/posts/$postId'
    | '/chat/'
    | '/course/'
    | '/deep-course/'
    | '/exercise/'
    | '/posts/'
    | '/deep-course/$deepcourseId/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/signup'
    | '/chat/$id'
    | '/course/$id'
    | '/deep-course/$deepcourseId'
    | '/exercise/$id'
    | '/layer'
    | '/posts/$postId'
    | '/chat'
    | '/course'
    | '/deep-course'
    | '/exercise'
    | '/posts'
    | '/deep-course/$deepcourseId/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/logout'
    | '/search'
    | '/settings'
    | '/signup'
    | '/_authed/chat'
    | '/_authed/course'
    | '/_authed/exercise'
    | '/_authed/posts'
    | '/_authed/deep-course'
    | '/_authed/chat/$id'
    | '/_authed/course/$id'
    | '/_authed/deep-course/$deepcourseId'
    | '/_authed/exercise/$id'
    | '/_authed/layer'
    | '/_authed/layer/__layout'
    | '/_authed/posts/$postId'
    | '/_authed/chat/'
    | '/_authed/course/'
    | '/_authed/deep-course/'
    | '/_authed/exercise/'
    | '/_authed/posts/'
    | '/_authed/deep-course/$deepcourseId/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/layer': {
      id: '/_authed/layer'
      path: '/layer'
      fullPath: '/layer'
      preLoaderRoute: typeof AuthedLayerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deep-course': {
      id: '/_authed/deep-course'
      path: '/deep-course'
      fullPath: '/deep-course'
      preLoaderRoute: typeof AuthedDeepCourseRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/exercise': {
      id: '/_authed/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof AuthedExerciseRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/course': {
      id: '/_authed/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof AuthedCourseRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/_authed/exercise/': {
      id: '/_authed/exercise/'
      path: '/'
      fullPath: '/exercise/'
      preLoaderRoute: typeof AuthedExerciseIndexRouteImport
      parentRoute: typeof AuthedExerciseRouteRoute
    }
    '/_authed/deep-course/': {
      id: '/_authed/deep-course/'
      path: '/'
      fullPath: '/deep-course/'
      preLoaderRoute: typeof AuthedDeepCourseIndexRouteImport
      parentRoute: typeof AuthedDeepCourseRoute
    }
    '/_authed/course/': {
      id: '/_authed/course/'
      path: '/'
      fullPath: '/course/'
      preLoaderRoute: typeof AuthedCourseIndexRouteImport
      parentRoute: typeof AuthedCourseRouteRoute
    }
    '/_authed/chat/': {
      id: '/_authed/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthedChatIndexRouteImport
      parentRoute: typeof AuthedChatRouteRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/_authed/layer/__layout': {
      id: '/_authed/layer/__layout'
      path: '/layer'
      fullPath: '/layer'
      preLoaderRoute: typeof AuthedLayer_layoutRouteImport
      parentRoute: typeof AuthedLayerRoute
    }
    '/_authed/exercise/$id': {
      id: '/_authed/exercise/$id'
      path: '/$id'
      fullPath: '/exercise/$id'
      preLoaderRoute: typeof AuthedExerciseIdRouteImport
      parentRoute: typeof AuthedExerciseRouteRoute
    }
    '/_authed/deep-course/$deepcourseId': {
      id: '/_authed/deep-course/$deepcourseId'
      path: '/$deepcourseId'
      fullPath: '/deep-course/$deepcourseId'
      preLoaderRoute: typeof AuthedDeepCourseDeepcourseIdRouteImport
      parentRoute: typeof AuthedDeepCourseRoute
    }
    '/_authed/course/$id': {
      id: '/_authed/course/$id'
      path: '/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof AuthedCourseIdRouteImport
      parentRoute: typeof AuthedCourseRouteRoute
    }
    '/_authed/chat/$id': {
      id: '/_authed/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthedChatIdRouteImport
      parentRoute: typeof AuthedChatRouteRoute
    }
    '/_authed/deep-course/$deepcourseId/$chapterId': {
      id: '/_authed/deep-course/$deepcourseId/$chapterId'
      path: '/$chapterId'
      fullPath: '/deep-course/$deepcourseId/$chapterId'
      preLoaderRoute: typeof AuthedDeepCourseDeepcourseIdChapterIdRouteImport
      parentRoute: typeof AuthedDeepCourseDeepcourseIdRoute
    }
  }
}

interface AuthedChatRouteRouteChildren {
  AuthedChatIdRoute: typeof AuthedChatIdRoute
  AuthedChatIndexRoute: typeof AuthedChatIndexRoute
}

const AuthedChatRouteRouteChildren: AuthedChatRouteRouteChildren = {
  AuthedChatIdRoute: AuthedChatIdRoute,
  AuthedChatIndexRoute: AuthedChatIndexRoute,
}

const AuthedChatRouteRouteWithChildren = AuthedChatRouteRoute._addFileChildren(
  AuthedChatRouteRouteChildren,
)

interface AuthedCourseRouteRouteChildren {
  AuthedCourseIdRoute: typeof AuthedCourseIdRoute
  AuthedCourseIndexRoute: typeof AuthedCourseIndexRoute
}

const AuthedCourseRouteRouteChildren: AuthedCourseRouteRouteChildren = {
  AuthedCourseIdRoute: AuthedCourseIdRoute,
  AuthedCourseIndexRoute: AuthedCourseIndexRoute,
}

const AuthedCourseRouteRouteWithChildren =
  AuthedCourseRouteRoute._addFileChildren(AuthedCourseRouteRouteChildren)

interface AuthedExerciseRouteRouteChildren {
  AuthedExerciseIdRoute: typeof AuthedExerciseIdRoute
  AuthedExerciseIndexRoute: typeof AuthedExerciseIndexRoute
}

const AuthedExerciseRouteRouteChildren: AuthedExerciseRouteRouteChildren = {
  AuthedExerciseIdRoute: AuthedExerciseIdRoute,
  AuthedExerciseIndexRoute: AuthedExerciseIndexRoute,
}

const AuthedExerciseRouteRouteWithChildren =
  AuthedExerciseRouteRoute._addFileChildren(AuthedExerciseRouteRouteChildren)

interface AuthedPostsRouteRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteRouteChildren: AuthedPostsRouteRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteRouteWithChildren =
  AuthedPostsRouteRoute._addFileChildren(AuthedPostsRouteRouteChildren)

interface AuthedDeepCourseDeepcourseIdRouteChildren {
  AuthedDeepCourseDeepcourseIdChapterIdRoute: typeof AuthedDeepCourseDeepcourseIdChapterIdRoute
}

const AuthedDeepCourseDeepcourseIdRouteChildren: AuthedDeepCourseDeepcourseIdRouteChildren =
  {
    AuthedDeepCourseDeepcourseIdChapterIdRoute:
      AuthedDeepCourseDeepcourseIdChapterIdRoute,
  }

const AuthedDeepCourseDeepcourseIdRouteWithChildren =
  AuthedDeepCourseDeepcourseIdRoute._addFileChildren(
    AuthedDeepCourseDeepcourseIdRouteChildren,
  )

interface AuthedDeepCourseRouteChildren {
  AuthedDeepCourseDeepcourseIdRoute: typeof AuthedDeepCourseDeepcourseIdRouteWithChildren
  AuthedDeepCourseIndexRoute: typeof AuthedDeepCourseIndexRoute
}

const AuthedDeepCourseRouteChildren: AuthedDeepCourseRouteChildren = {
  AuthedDeepCourseDeepcourseIdRoute:
    AuthedDeepCourseDeepcourseIdRouteWithChildren,
  AuthedDeepCourseIndexRoute: AuthedDeepCourseIndexRoute,
}

const AuthedDeepCourseRouteWithChildren =
  AuthedDeepCourseRoute._addFileChildren(AuthedDeepCourseRouteChildren)

interface AuthedLayerRouteChildren {
  AuthedLayer_layoutRoute: typeof AuthedLayer_layoutRoute
}

const AuthedLayerRouteChildren: AuthedLayerRouteChildren = {
  AuthedLayer_layoutRoute: AuthedLayer_layoutRoute,
}

const AuthedLayerRouteWithChildren = AuthedLayerRoute._addFileChildren(
  AuthedLayerRouteChildren,
)

interface AuthedRouteChildren {
  AuthedChatRouteRoute: typeof AuthedChatRouteRouteWithChildren
  AuthedCourseRouteRoute: typeof AuthedCourseRouteRouteWithChildren
  AuthedExerciseRouteRoute: typeof AuthedExerciseRouteRouteWithChildren
  AuthedPostsRouteRoute: typeof AuthedPostsRouteRouteWithChildren
  AuthedDeepCourseRoute: typeof AuthedDeepCourseRouteWithChildren
  AuthedLayerRoute: typeof AuthedLayerRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatRouteRoute: AuthedChatRouteRouteWithChildren,
  AuthedCourseRouteRoute: AuthedCourseRouteRouteWithChildren,
  AuthedExerciseRouteRoute: AuthedExerciseRouteRouteWithChildren,
  AuthedPostsRouteRoute: AuthedPostsRouteRouteWithChildren,
  AuthedDeepCourseRoute: AuthedDeepCourseRouteWithChildren,
  AuthedLayerRoute: AuthedLayerRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CalendarRoute: CalendarRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
